# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\rehay\Desktop\SWE599\bounsteg_retrieve.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_retrieveData(object):
    def setupUi(self, retrieveData):
        retrieveData.setObjectName("retrieveData")
        retrieveData.resize(488, 341)
        self.filePath2 = QtWidgets.QLineEdit(retrieveData)
        self.filePath2.setEnabled(False)
        self.filePath2.setGeometry(QtCore.QRect(20, 60, 291, 20))
        self.filePath2.setObjectName("filePath2")
        self.browseImage2 = QtWidgets.QPushButton(retrieveData)
        self.browseImage2.setGeometry(QtCore.QRect(360, 60, 81, 21))
        self.browseImage2.setObjectName("browseImage2")
        self.secretFileName = QtWidgets.QLineEdit(retrieveData)
        self.secretFileName.setEnabled(False)
        self.secretFileName.setGeometry(QtCore.QRect(20, 250, 291, 20))
        self.secretFileName.setReadOnly(True)
        self.secretFileName.setObjectName("secretFileName")
        self.saveAsText = QtWidgets.QPushButton(retrieveData)
        self.saveAsText.setEnabled(False)
        self.saveAsText.setGeometry(QtCore.QRect(360, 210, 81, 21))
        self.saveAsText.setObjectName("saveAsText")
        self.extractFile = QtWidgets.QPushButton(retrieveData)
        self.extractFile.setEnabled(False)
        self.extractFile.setGeometry(QtCore.QRect(360, 250, 81, 21))
        self.extractFile.setObjectName("extractFile")
        self.line = QtWidgets.QFrame(retrieveData)
        self.line.setGeometry(QtCore.QRect(10, 110, 461, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.radioembed2 = QtWidgets.QRadioButton(retrieveData)
        self.radioembed2.setGeometry(QtCore.QRect(20, 10, 82, 17))
        self.radioembed2.setChecked(False)
        self.radioembed2.setObjectName("radioembed2")
        self.radioRetrieve2 = QtWidgets.QRadioButton(retrieveData)
        self.radioRetrieve2.setGeometry(QtCore.QRect(160, 10, 111, 17))
        self.radioRetrieve2.setChecked(True)
        self.radioRetrieve2.setObjectName("radioRetrieve2")
        self.label = QtWidgets.QLabel(retrieveData)
        self.label.setGeometry(QtCore.QRect(20, 40, 291, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.imageInfo2 = QtWidgets.QLabel(retrieveData)
        self.imageInfo2.setGeometry(QtCore.QRect(20, 90, 451, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.imageInfo2.setFont(font)
        self.imageInfo2.setText("")
        self.imageInfo2.setObjectName("imageInfo2")
        self.secretText2 = QtWidgets.QTextEdit(retrieveData)
        self.secretText2.setEnabled(False)
        self.secretText2.setGeometry(QtCore.QRect(20, 160, 291, 71))
        self.secretText2.setReadOnly(True)
        self.secretText2.setAcceptRichText(False)
        self.secretText2.setObjectName("secretText2")
        self.copyText = QtWidgets.QPushButton(retrieveData)
        self.copyText.setEnabled(False)
        self.copyText.setGeometry(QtCore.QRect(360, 160, 81, 21))
        self.copyText.setObjectName("copyText")

        self.retranslateUi(retrieveData)
        QtCore.QMetaObject.connectSlotsByName(retrieveData)

    def retranslateUi(self, retrieveData):
        _translate = QtCore.QCoreApplication.translate
        retrieveData.setWindowTitle(_translate("retrieveData", "BounSteg"))
        self.filePath2.setText(_translate("retrieveData", "1) Choose an image to start..."))
        self.browseImage2.setText(_translate("retrieveData", "Browse Image"))
        self.saveAsText.setText(_translate("retrieveData", "Save As Txt"))
        self.extractFile.setText(_translate("retrieveData", "Extract File"))
        self.radioembed2.setText(_translate("retrieveData", "Embed Data"))
        self.radioRetrieve2.setText(_translate("retrieveData", "Retrieve Data"))
        self.label.setText(_translate("retrieveData", "Choose an image to see hidden data (if it has)"))
        self.copyText.setText(_translate("retrieveData", "Copy"))
